import type {Plan,Activity,Source} from './types';
export async function api<T>(path:string,body?:unknown):Promise<T>{
 const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),body?180000:20000);
 try{const response=await fetch('/api'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:controller.signal});let result;try{result=await response.json();}catch{throw new Error('服务返回了无法读取的内容，请稍后重试。');}if(!response.ok)throw new Error(typeof result.detail==='string'?result.detail:result.error||'请求未完成，请检查服务连接。');return result as T;}catch(error){if(error instanceof Error&&error.name==='AbortError')throw new Error('本次请求超时，请稍后重试；已有行程已保留。');throw error;}finally{clearTimeout(timer);}
}
const object=(value:unknown):value is Record<string,unknown>=>value!==null&&typeof value==='object'&&!Array.isArray(value);
const strings=(value:unknown):value is string[]=>Array.isArray(value)&&value.every(s=>typeof s==='string');
const finite=(value:unknown)=>typeof value==='number'&&Number.isFinite(value);
export function validPlan(value:unknown):value is Plan{if(!object(value))return false;return ['id','title','destination','origin','start_date','end_date','summary'].every(key=>typeof value[key]==='string')&&finite(value.travelers)&&finite(value.budget)&&['demo','live','limited'].includes(String(value.mode))&&Array.isArray(value.days)&&value.days.length>0&&value.days.length<=7&&value.days.every(day=>object(day)&&['date','title','description'].every(key=>typeof day[key]==='string')&&Array.isArray(day.activities)&&day.activities.length<=40&&day.activities.every(a=>object(a)&&['id','time','end_time','title','description','transport_note'].every(key=>typeof a[key]==='string')&&finite(a.duration_minutes)&&Number(a.duration_minutes)>0&&finite(a.cost)&&strings(a.source_ids)&&typeof a.verified==='boolean'&&typeof a.indoor==='boolean')&&(!day.weather||(object(day.weather)&&typeof day.weather.description==='string'&&typeof day.weather.status==='string'&&typeof day.weather.source_url==='string'&&(day.weather.temp_min===null||finite(day.weather.temp_min))&&(day.weather.temp_max===null||finite(day.weather.temp_max)))))&&validSources(value.sources)&&strings(value.warnings)&&strings(value.tips)&&Array.isArray(value.cost_breakdown)&&value.cost_breakdown.every(row=>object(row)&&typeof row.label==='string'&&finite(row.amount));}
export function readStore<T>(key:string,fallback:T,validate:(v:unknown)=>boolean):T{try{const v=JSON.parse(localStorage.getItem('manyou.v1.'+key)||'null');return validate(v)?v as T:fallback;}catch{return fallback;}}
export function writeStore(key:string,value:unknown){try{localStorage.setItem('manyou.v1.'+key,JSON.stringify(value));return true;}catch{return false;}}
export function validSources(value:unknown):value is Source[]{return Array.isArray(value)&&value.length<=200&&value.every(s=>object(s)&&['id','title','url','excerpt'].every(key=>typeof s[key]==='string')&&['xiaohongshu','douyin','official','web','sample'].includes(String(s.platform))&&['full','snippet','sample','unavailable'].includes(String(s.content_status)));}
export function safeUrl(url:string){try{const u=new URL(url);return u.protocol==='http:'||u.protocol==='https:'?u.href:undefined;}catch{return undefined;}}
export const shortDate=(date:string)=>{const d=new Date(date+'T12:00:00');return Number.isNaN(d.getTime())?date:(d.getMonth()+1)+'月'+d.getDate()+'日';};
export const weekday=(date:string)=>{const d=new Date(date+'T12:00:00');return Number.isNaN(d.getTime())?'':['周日','周一','周二','周三','周四','周五','周六'][d.getDay()];};
export function recalc(activities:Activity[]):Activity[]{let mins=9*60;return activities.map((a,index)=>{const duration=Number(a.duration_minutes);if(!Number.isFinite(duration)||duration<=0)throw new Error('停留时长无效，请重新生成行程。');const time=clock(mins);mins+=duration;if(mins>=24*60)throw new Error('调整后行程将跨越午夜，请先减少当天地点或停留时长。');const end_time=clock(mins);if(index<activities.length-1)mins+=20;return {...a,time,end_time};});}
function clock(mins:number){return String(Math.floor(mins/60)).padStart(2,'0')+':'+String(mins%60).padStart(2,'0');}
export function toMarkdown(plan:Plan){return '# '+plan.title+'\n\n'+plan.start_date+' — '+plan.end_date+' · '+plan.travelers+' 人\n\n'+plan.summary+'\n\n'+(plan.mode==='demo'?'> 本行程为演示样例，不代表实时检索结果。\n\n':'')+plan.days.map((day,i)=>'## DAY '+(i+1)+' · '+shortDate(day.date)+' '+day.title+'\n\n'+day.activities.map(a=>'### '+a.time+'–'+a.end_time+' '+a.title+'\n\n'+a.description+'\n\n停留 '+a.duration_minutes+' 分钟 · '+(a.cost?'参考费用 ¥'+a.cost:'费用待确认')+'\n\n'+(a.transport_note||'')+'\n\n').join('')).join('')+'## 预算估算\n\n'+plan.cost_breakdown.map(item=>'- '+item.label+'：¥'+item.amount).join('\n')+'\n\n实际价格以预订时为准。\n\n## 天气信息\n\n'+plan.days.map(d=>'- '+d.date+'：'+(d.weather?d.weather.description+' '+(d.weather.temp_min??'暂无')+'° / '+(d.weather.temp_max??'暂无')+'° · 状态：'+d.weather.status+' · 来源：'+d.weather.source_url:'暂无可用天气')).join('\n')+'\n\n## 来源\n\n'+plan.sources.map(s=>'- '+s.title+'：'+s.url+'（'+s.content_status+'）').join('\n')+'\n\n## 提醒\n\n'+[...plan.tips,...plan.warnings].map(t=>'- '+t).join('\n');}
export function downloadPlan(plan:Plan){const blob=new Blob([toMarkdown(plan)],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=plan.title.replace(/[<>:"/\\|?*]/g,'')+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
